# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyBikXEZAuziRdh5P4oatM4-7r71vTMM
"""

import pandas as pd
import numpy as np


df = pd.read_csv('/content/world_happiness_2023.csv')
df.columns = ['Country','Region','Happiness_Score','GDP','Social_Support',
              'Life_Expectancy','Freedom','Generosity','Corruption']


print(f"Dataset: {len(df)} countries, {len(df.columns)} columns")
print(df.head())

import plotly.express as px
import plotly.graph_objects as go

# Explore the dataset before you start
print("Regions in dataset:")
print(df['Region'].value_counts())
print("\nScore range:", df['Happiness_Score'].min(), "–", df['Happiness_Score'].max())
print("\nBottom 10 countries:")
print(df.nsmallest(10, 'Happiness_Score')[['Country','Region','Happiness_Score']])

"""Task 1: Regional comparison bar chart"""

region_avg = (df.groupby('Region')['Happiness_Score']
              .mean()
              .reset_index()
              .sort_values('Happiness_Score'))  # sort for horizontal bar

print(region_avg)

import plotly.express as px

fig = px.bar(
    region_avg,
    x='Happiness_Score',
    y='Region',
    orientation='h',
    title='Western Europe is the happiest region, revealing a clear gap in global well-being',
    labels={'Happiness_Score': 'Average Happiness Score', 'Region': ''},
    color='Happiness_Score',
    color_continuous_scale='Sunset'
)


fig.update_layout(
    xaxis=dict(range=[0, region_avg['Happiness_Score'].max() + 1]),
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_gridcolor='#EEEEEE',
    yaxis_gridcolor='white'

)

fig.update_traces(marker_line_width=0)

fig.show()

"""Task 2: Top 8 vs. Bottom 8 contrast"""

top8 = df.nlargest(8, 'Happiness_Score').copy()
top8['Group'] = 'Top 8'
bottom8 = df.nsmallest(8, 'Happiness_Score').copy()
bottom8['Group'] = 'Bottom 8'

combined = pd.concat([bottom8, top8]).sort_values('Happiness_Score')
global_avg = df['Happiness_Score'].mean()
print(f"Global average: {global_avg:.2f}")

import plotly.express as px
import pandas as pd

# Get top 8 and bottom 8
top8 = df.nlargest(8, 'Happiness_Score').copy()
top8['Group'] = 'Top 8'

bottom8 = df.nsmallest(8, 'Happiness_Score').copy()
bottom8['Group'] = 'Bottom 8'

# Combine and sort
combined = pd.concat([bottom8, top8]).sort_values('Happiness_Score')

# Global average
global_avg = df['Happiness_Score'].mean()

# Create chart
fig = px.bar(
    combined,
    x='Happiness_Score',
    y='Country',
    orientation='h',
    color='Group',
    color_discrete_map={
        'Top 8': '#52B788',     # gold (happy)
        'Bottom 8': '#5E81AC'   # blue (less happy)
    },
    title='A dramatic global gap: the happiest countries score nearly double the least happy',
    labels={'Happiness_Score': 'Happiness Score', 'Country': ''}
)

# Add global average line (visual separator)
fig.add_vline(
    x=global_avg,
    line_dash="dash",
    line_color="black"
)

# Add annotation
fig.add_annotation(
    x=global_avg,
    y=0,
    text="Global Average",
    showarrow=False,
    yshift=10
)

# Clean layout + zero baseline
fig.update_layout(
    xaxis=dict(range=[0, combined['Happiness_Score'].max() + 1]),
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_gridcolor='#EEEEEE',
    yaxis_gridcolor='white'
)

# Final polish
fig.update_traces(marker_line_width=0)

fig.show()

"""Stretch Goal"""

import plotly.express as px
import pandas as pd

# Select required regions
regions = [
    'Western Europe',
    'Latin America and Caribbean',
    'East Asia',
    'Sub-Saharan Africa',
    'South Asia'
]

filtered = df[df['Region'].isin(regions)]

# Compute averages
region_factors = (
    filtered.groupby('Region')[['GDP', 'Freedom']]
    .mean()
    .reset_index()
)

# Convert to long format
region_long = region_factors.melt(
    id_vars='Region',
    value_vars=['GDP', 'Freedom'],
    var_name='Factor',
    value_name='Value'
)

# Create grouped bar chart
fig = px.bar(
    region_long,
    x='Region',
    y='Value',
    color='Factor',
    barmode='group',
    title='Western Europe leads in both economic strength and freedom, highlighting global inequality across regions',
    labels={'Value': 'Average Score', 'Region': '', 'Factor': ''},
    color_discrete_map={
        'GDP': '#52B788',       # pleasant green
        'Freedom': '#5E81AC'    # soft blue
    }
)

# Clean layout
fig.update_layout(
    plot_bgcolor='white',
    paper_bgcolor='white',
    xaxis_gridcolor='#EEEEEE',
    yaxis_gridcolor='#EEEEEE',
    legend_title_text=''
)

# Final polish
fig.update_traces(marker_line_width=0)

fig.show()